CREATE TABLE AUDITTABLE (
  ID INTEGER PRIMARY KEY,
  Username VARCHAR(255) NOT NULL,
  KeyFieldID INTEGER NOT NULL,
  ActionType INTEGER NOT NULL,
  DateTimeStamp DATE NOT NULL,
  DataModel VARCHAR(50) NOT NULL,
  Changes VARCHAR(255) NOT NULL,
  ValueBefore VARCHAR(255) NOT NULL,
  ValueAfter VARCHAR(255) NOT NULL,
);